CREATE DATABASE DB_APOIOVERDE;
USE DB_APOIOVERDE;

CREATE TABLE TB_USUARIO(
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    SENHA VARCHAR(8) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    ATIVO BIT NOT NULL,
    
    PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE TB_INFO_USUARIO(
	ID INT NOT NULL AUTO_INCREMENT,
    LOGRADOURO VARCHAR(50),
    NUMERO VARCHAR(15),
    BAIRRO VARCHAR(15),
    CEP VARCHAR(40),
    CIDADE VARCHAR(20),
    ESTADO VARCHAR(2),
    TELEFONE VARCHAR(15),
    CPF VARCHAR(11),
    
    MARCA VARCHAR(20),
    HISTORIA VARCHAR(500),
    CNPJ VARCHAR(23),
    
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID)
)ENGINE=InnoDB;


CREATE TABLE TB_PROJETO(
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(15) NOT NULL,
    OQUE_APOIAREI VARCHAR(200),
    OQUE_RECEBEREI VARCHAR(200),
    QUANDO_RECEBEREI VARCHAR(200),
    VALOR DECIMAL(8,2),
    META_FINAL DECIMAL(8,2),
    ESTADO CHAR(3),
    DATA_ENTREGA DATETIME,
    IMAGEM VARCHAR(300),
    
    ID_PRODUTOR INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PRODUTOR) REFERENCES TB_USUARIO (ID)
)ENGINE=InnoDB;

CREATE TABLE TB_PEDIDO(
	ID INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    DATA_MODIFICACAO DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_USUARIO (ID),
    FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETO (ID)
)ENGINE=InnoDB;

